config/routes.rb
GtlSecond::Application.routes.draw do

  root :to => "home#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :groups

  resources :groups do
    resources :items
    resources :purchases
    resources :group_users, only: [:create, :destroy]
  end

  get '/users/:id', to: 'users#show', as: 'user'

end

app/models/group.rb
class Group<ActiveRecord::Base
  validates_presence_of :name

  has_many :group_users,
    inverse_of: :group

  has_many :users,
    through: :group_users

  has_many :items,
    inverse_of: :group

  has_many :purchases,
    inverse_of: :group,
    through: :group_users,
    dependent: :destroy

  def ordered_recent_purchases
    self.purchases.order('created_at DESC').limit(10)
  end

  def purchased_items
    self.items.where('purchase_id is NOT NULL')
  end

  def unpurchased_items
    self.items.where('purchase_id is NULL')
  end

  def total_spent_unsettled
    total =0.00
    self.purchases.where(settled_at: nil).each do |purchase|
      total += purchase.cost
    end
    total
  end

end

app/controllers/groups_controller.rb
class GroupsController<ApplicationController
before_action :set_group, only: [:edit, :update, :destroy, :show]
before_action :authorize_user, except: [:new, :create]

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group_user = GroupUser.new
  end

  def update
    if @group.update(group_params)
      redirect_to edit_group_path(@group)
    else
      render 'edit'
    end
  end

  def index
    if user_signed_in?
      @groups = current_user.groups
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @group.destroy
    redirect_to group_path(current_user.default_group)
  end

  def show
    @groups = current_user.groups
    @item = Item.new
    @group_user = GroupUser.new
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

  # makes sure that user is logged in and is part of the group that they want to view
  def authorize_user
    unless user_signed_in? && current_user.groups.include?(Group.find(params[:id]))
      raise ActionController::RoutingError.new('Not Found')
    end
  end


end

app/views/groups/_edit_group_members.html.erb
<table class="custom-table">
  <tbody>
    <thead>
      <tr>
        <th colspan=3>
          <h4>Members</h4>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>$ Spent</th>
        <th>Owed/Owes</th>
      </tr>
    </thead>
    <% @group.users.each do |user| %>
      <tr>
        <td><span data-tooltip class="has-tip" title=<%=user.email%>><%= user.name %></span></td>
        <td><%= user.find_membership(@group).spent_for_group %></td>
        <% if user.find_membership(@group).owed%>
          <td class=owed>Owed:<%= user.find_membership(@group).owed %></td>
        <% elsif user.find_membership(@group).owes%>
          <td class=owes>Owes:<%= user.find_membership(@group).owes%></td>
        <% else %>
          <td></td>
        <% end%>
      </tr>
    <% end %>
      <tr>
        <td>
          <a href="#" data-reveal-id="myModal" class="button tiny">Add Member</a>
          <div id="myModal" class="reveal-modal" data-reveal>
            <p>Add someone to <%=@group.name%></p>
            <%= simple_form_for [@group, @group_user], controller: :group_user, action: :create do |f|%>
              <%= f.input :email_address %>
              <%= f.button :submit, "Add Member", class: "tiny" %>
            <%end%>
            <a class="close-reveal-modal">&#215;</a>
          </div>
        </td>
        <td></td>
        <td><%= link_to "Remove Me From This Group", group_group_user_path(@group, current_user.find_membership(@group)), data: {confirm: "Are you sure you want to remove yourself from #{@group.name}?"}, method: :delete %></td>
      </tr>

  </tbody>
</table>

app/views/groups/_edit_group_name.html.erb
<%= simple_form_for(@group) do |f| %>
<div class="add-item-form form-inline">
  <h1>Make Changes to <%=@group.name%></h1>
  <%= f.input_field :name %>
  <%= button_tag(type: 'submit', class: "rename-group-button tiny ") do%>
      Rename Group
  <%end%>
</div>
<% end %>

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
<div class="add-item-form form-inline">
  <%= f.input_field :name %>
  <%= button_tag(type: 'submit', class: "rename-group-button tiny ") do%>
      Rename Group
  <%end%>
</div>
<% end %>

app/views/groups/_group_purchases.html.erb
<div class="purchases">
  <table class= "custom-table">
    <thead>
      <tr>
        <th colspan="3">
          <h4><%= link_to "#{@group.name}'s Purchases", group_purchases_path(@group) %></h4>
        </th>
      </tr>
      <tr>
        <th>Made By:</th>
        <th>Cost:</th>
        <th>Made on:</th>
      </tr>
    </thead>
    <tbody>
      <% @group.ordered_recent_purchases.each do |purchase| %>
        <tr class="purchase-row" data-link="<%= group_purchase_path(@group, purchase)%>">
          <td><%= "#{purchase.user_name}"%></td>
          <td><%= purchase.cost %></td>
          <td><%= purchase.formatted_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/_members.html.erb
<table class= "custom-table">
  <tbody>
      <thead>
        <tr>
          <th colspan="3"><h4>Members</h4></th>
        </tr>
        <tr>
          <th>Name</th>
          <th>$ Spent</th>
          <th>Owed/Owes</th>
        </tr>
      </thead>
    <% @group.users.each do |user| %>
      <tr>
        <td><span data-tooltip class="has-tip" title=<%=user.email%>><%= user.name %></span></td>
        <td><%= user.find_membership(@group).spent_for_group %></td>
        <% if user.find_membership(@group).owed%>
          <td class=owed>Owed:<%= user.find_membership(@group).owed %></td>
        <% elsif user.find_membership(@group).owes%>
          <td class=owes>Owes:<%= user.find_membership(@group).owes%></td>
        <% else %>
          <td></td>
        <% end%>
      </tr>
    <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
      </tr>

  </tbody>
</table>

app/views/groups/_your_groups.html.erb
<table class="groups-table custom-table">
  <tbody>
    <thead>
      <tr>
        <th colspan="2">
          <h4>Groups</h4>
        </th>
      </tr>
    </thead>
    <% current_user.groups.each do |group| %>
      <%if group.name == @group.name%>
        <tr class="group-row chosen-group" data-link="<%= group_path(group)%>">
          <td colspan="2"><%=group.name%></td>
        </tr>
      <% else %>
        <tr class="group-row" data-link="<%= group_path(group)%>">
          <td colspan="2"><%=group.name%></td>
        </tr>
      <% end %>
    <% end%>
    <tr>
      <td><%= link_to 'New Group', new_group_path, class: "tiny button"%>
      </td>
      <td><%= link_to "Edit Group", edit_group_path(@group)%>
      </td>
    </tr>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="small-11 medium-8 columns small-centered">

  <%= render 'edit_group_name' %>
</div>

<div class="small-11 medium-8 columns small-centered">
  <%= render 'edit_group_members' %>

  <%= link_to 'Back', group_path(@group), class:"button back-btn"%>

  <%= link_to 'Destroy Group', group_path(@group), method: :delete, data: { confirm: 'This group will no longer belong to other users. Are you sure you want to delete this group?' }, class:"tiny button destroy-btn" %>




</div>

app/views/groups/index.html.erb
<%content_for :left_side_bar do %>

<p>
  <strong>Name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>Amount Spent This Month:</strong>
  <%= current_user.total_spent_in_current_month %>
</p>

<% end %>

<%content_for :main_title do %>
  <div class="medium-12 columns group-name">

  </div>


<%end%>


<div class="main-wrapper">

</div>


<%content_for :right_side_bar do%>
  <div id="your-groups">
    <%= render 'your_groups' %>
  </div>
<% end %>

app/views/groups/new.html.erb
<div class="medium-6 columns medium-centered faded-background>">

  <%= render 'form' %>

</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="small-12 small-pull-12 medium-3 large-3 columns" id="left-content">

    <div id="your-groups" class="hide-mobile">
      <%= render 'your_groups' %>
    </div>

    <div id="members">
      <%= render 'members' %>
    </div>

    <br>

  </div>


  <%content_for :main_title do %>
    <div class="medium-12 columns group-name">
      <h1 class="cover-logo"><%=@group.name%></h1>
    </div>
  <%end%>

  <div class="small-12 small-push-12 medium-6 large-6 columns" id="main-content">

    <div class="items-form">
      <%= render 'items/form', group: @group %>
    </div>

    <table class="custom-table">
      <% @group.unpurchased_items.each do |item| %>
       <tr>
        <td>
          </i><span class="item"><%= item.name %></span><%=link_to "<i class='fi-x-circle large'></i>".html_safe, group_item_path(@group, item), method: :delete%>
        </td>
        </tr>
      <% end %>
    </table>

      <%= link_to 'Make a Purchase', new_group_purchase_path(@group), class: "button purchase-button" %>

  </div>


  <div class="small-12 medium-3 large-3 columns" id="right-content">
    <div id="purchases">
      <%= render 'group_purchases' %>
    </div>
  </div>
</div>