config/routes.rb
GtlSecond::Application.routes.draw do

  root :to => "home#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :groups

  resources :groups do
    resources :items
    resources :purchases
    resources :group_users, only: [:create, :destroy]
  end

  get '/users/:id', to: 'users#show', as: 'user'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]
  # before_action :authorize_user

# GET /purchases
  # GET /purchases.json
  def index
    @group = Group.find(params[:group_id])
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @group = Group.find(params[:group_id])
  end

  # GET /purchases/new
  def new
    @group = Group.find(params[:group_id])
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
    @group = Group.find(params[:group_id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @group = Group.find(params[:group_id])
    @user = current_user
    @group_user = GroupUser.where(group_id: params[:group_id], user_id: current_user.id).first
    @purchase = @group_user.purchases.build(purchase_params)
    if @purchase.make_purchase(purchase_params[:item_ids])
      redirect_to group_purchase_path(@group, @purchase), notice: 'purchase was successfully created!'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /issues/1.json
  def update
    @group = Group.find(params[:group_id])
    if @purchase.update(purchase_params)
      redirect_to group_purchase_path(@group,@purchase), notice: 'purchase was successfully updated!'
    else
      render action: 'edit'
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @group = Group.find(params[:group_id])
    @purchase.destroy
    redirect_to group_purchases_path(@group)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white purchase through.
    def purchase_params
      params.require(:purchase).permit(:cost, :user_id, :group_id, :receipt_photo, item_ids: []  )
    end

    def authorize_user
      unless user_signed_in? and current_user.is_admin?
        raise ActionController::RoutingError.new('Not Found')
      end
    end
end

app/views/purchases/_form.html.erb
 <div class="purchases-form">
   <%= simple_form_for [@group, @purchase] do |f| %>
    <% if @purchase.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this issue from being saved:</h2>

        <ul>
        <% @purchase.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.input :cost %>

    <div class="row">
      <div class="medium-6 columns">
      <%= f.association :items, as: :check_boxes, item_wrapper_class: 'item-check-boxes', collection: @group.unpurchased_items%>
      </div>
    </div>

    <div>
      <%= f.label :receipt_photo, "Receipt Photo" %>
      <%= f.file_field :receipt_photo %>
    </div>
    <%= f.button :submit %>

  <% end %>
</div>

app/views/purchases/_purchased_form.html.erb
<%= simple_form_for [@group, @purchase] do |f| %>
    <% if current_user == @purchase.user %>
      <h2>Make Changes to your purchase on <%=@purchase.formatted_date%> </h2>
    <% else %>
      <h2>Make Changes to Purchase <%=@purchase.formatted_date%> made by <%= @purchase.user.name%></h2>
    <% end %>

  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :cost %>

  <% @purchase.items.each do |item|%>
  <%= item.name %><br>
  <% end %><br>

  <%= image_tag @purchase.receipt_photo_url.to_s %>

  <%= f.button :submit %>

<% end %>

app/views/purchases/edit.html.erb
<div class="medium-6 columns medium-centered faded-background" id="purchase-show">

<%= render 'purchased_form' %>


<%= link_to 'Show', group_purchase_path(@group, @purchase) %> |
<%= link_to 'Back', group_purchases_path(@group) %>

</div>

app/views/purchases/index.html.erb
<div class="row">
  <div class="small-12 small-push-12 medium-6 large-6 columns small-centered faded-background" id="main-content">

    <h2>Purchases</h2>

    <table>
      <thead>
        <tr>
          <th>Purchase</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @group.purchases.each do |purchase| %>
          <tr class="purchase-row">
            <td><%= link_to "#{purchase.formatted_date} by #{purchase.user_name}", group_purchase_path(@group,purchase) %></td>
            <td><%= link_to 'Delete Purchase', group_purchase_path(@group,purchase), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Purchase', new_group_purchase_path(@group) %> |

    <%= link_to "Back to #{@group.name}", group_path(@group) %>
  </div>
</div>

app/views/purchases/new.html.erb
<%content_for :main_title do %>
  <div class="medium-12 columns group-name">
    <h1>Make a Purchase for <%=@group.name %></h1>
  </div>
<% end %>

<div class="small-10 medium-8 columns small-centered faded-background">

  <%= render 'purchases/form' %>

  <%= link_to 'Back', group_path(@group) %>
</div>

app/views/purchases/show.html.erb
<div class="small-12 medium-8 columns faded-background" id="purchase-show">


  <% if @purchase.user == current_user %>
    <h3>Your Purchase on <%=@purchase.formatted_date%></h3>
  <% else %>
    <h3><%= "#{@purchase.user_name}'s purchase on #{@purchase.formatted_date}"%></h3>
  <%end%>
  <p>
    <strong>Purchased:</strong>
    <%= @purchase.formatted_date %>
  </p>

  <p>
    <strong>Group Purchased For:</strong>
    <%= @group.name %>
  </p>

  <p>
    <strong>Items:</strong>
    <% @purchase.items.each do |item| %>
        <% if @purchase.items.count > 1 %>
          <% if item == @purchase.items.last %>
            <%= "#{item.name}" %>
          <% else%>
            <%= "#{item.name}, " %>
          <%end%>
        <% else %>
          <%= item.name %>
        <% end %>
    <% end %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= @purchase.cost%>
  </p>

  <%= image_tag @purchase.receipt_photo_url.to_s %>

  <p>
  <%= link_to 'Edit purchase Info', edit_group_purchase_path(@group, @purchase) %>
  </p>

  <%= link_to "Back to #{@group.name}", group_path(@group), class: "button" %>


  <%content_for :right_side_bar do%>

    <div id="purchases" class="small-6 medium-4 columns">
      <%= render 'groups/group_purchases' %>
    </div>

    <br>

  <% end %>

</div>