config/routes.rb
GtlSecond::Application.routes.draw do

  root :to => "home#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :groups

  resources :groups do
    resources :items
    resources :purchases
    resources :group_users, only: [:create, :destroy]
  end

  get '/users/:id', to: 'users#show', as: 'user'

end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Grab The List", root_path%></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if user_signed_in? -%>
          <li class="has-dropdown display-mobile">
            <a href="#">My Groups</a>
            <ul class="dropdown">
              <% current_user.groups.each do |group|%>
              <li><%= link_to group.name, group %></li>
              <% end %>
              <li><%= link_to 'Add New Group +', new_group_path%></li>
            </ul>
          </li>
          <li><%= link_to "#{current_user.email}", user_path(current_user)%> </li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign In', new_user_session_path%></li>
          <li><%= link_to 'Sign Up', new_user_registration_path%></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Grab The List</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,300italic' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

  <% flash.each do |name, msg| -%>
    <div data-alert class="alert-box radius <%name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg, class: name %>
      <a href="#" class="close">&times;</a>
    </div>

  <% end -%>

    <div class="row">
      <div class="small-12 columns small-centered">
        <%= yield :main_title%>
      </div>
    </div>

    <div class="row">
      <%= yield %>
      <%= yield :right_side_bar%>
    </div>



    <%= javascript_include_tag "application" %>

    <script type="text/javascript">
      $(document).ready(function() {
        // $(".cover").backstretch("<%=image_path('cover.jpg')%>")
        // <%=image_path('wood-texture.jpg')%>
      $.backstretch("<%=image_path('wood-texture.jpg')%>")
        });
    </script>


 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47456904-2', 'grabthelist-production.herokuapp.com');
  ga('send', 'pageview');

</script>
  </body>
</html>